import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://ivjcbellwhtotulkthov.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2amNiZWxsd2h0b3R1bGt0aG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODMzMTQsImV4cCI6MjA1NDE1OTMxNH0.WveDkCUj_1uX5rgrjdyeO8ifmyj5TGjh_5w5QV73Iwo')